# Generated by Django 2.0.6 on 2018-06-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180625_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='ano',
            field=models.FloatField(),
        ),
    ]
